# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1fda10f655e4baded6af25d3a11310ad8e8d527f307884b9c3149c244236ecb9cc89ca8066bc63e6420362c8d747a1a31a756513e7d1ad2feedf393849ac2e6

test:
  secret_key_base: 464e43a68c082fcf6f60beb1b5c9f78e2b735b1b45e4a2013e421d14926461a415dbbe0720d2d0b98ef2a07cd42b1c7098319ec58dc28ca59452ece83490f371

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
